# Generated by Django 3.0.4 on 2020-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_benutzer_jahr'),
    ]

    operations = [
        migrations.AddField(
            model_name='benutzer',
            name='adresse',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
