# Generated by Django 3.0.4 on 2020-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_benutzer_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='benutzer',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benutzer',
            name='jahr',
            field=models.IntegerField(default=0),
        ),
    ]
