# Generated by Django 3.0.4 on 2020-03-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20200313_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benutzer',
            name='status',
        ),
    ]
