# Generated by Django 3.0.4 on 2020-03-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='start',
            new_name='stars',
        ),
    ]
